//
//  notefinalViewController.m
//  iosfinalproject
//
//  Created by haojue wang on 2017/11/25.
//  Copyright © 2017年 Unversity of Leeds. All rights reserved.
//

#import "notefinalViewController.h"

@interface notefinalViewController ()

@end

@implementation notefinalViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    
    //make the image look like a gif//all of image// the video i taken from https://www.youtube.com/watch?v=Euzfg2ieDvk
    NSArray *imageNames = @[@"Stabilo Holiday Flipbook - 'Free Your True Colors'001",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'002",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'003",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'004",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'005",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'006",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'007",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'008",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'009",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'010",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'011",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'012",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'013",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'014",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'015",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'016",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'017",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'018",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'019",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'020",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'021",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'022",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'023",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'024",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'025",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'026",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'027",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'028",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'029",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'030",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'031",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'032",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'033",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'034",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'035",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'036",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'037",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'038",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'039",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'040",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'041",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'042",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'043",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'044",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'045",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'046",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'047",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'048",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'049",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'050",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'051",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'052",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'053",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'054",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'055",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'056",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'057",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'058",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'059",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'060",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'061",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'062",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'063",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'064",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'065",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'066",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'067",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'068",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'069",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'070",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'071",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'072",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'073",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'074",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'075",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'076",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'077",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'078",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'079",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'080",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'081",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'082",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'083",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'084",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'085",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'086",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'087",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'088",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'089",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'090",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'091",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'092",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'093",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'094",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'095",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'096",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'097",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'098",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'099",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'100",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'101",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'102",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'103",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'104",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'105",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'106",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'107",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'108",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'109",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'110",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'111",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'112",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'113",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'114",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'115",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'116",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'117",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'118",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'119",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'120",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'121",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'122",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'123",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'124",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'125",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'126",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'127",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'128",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'129",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'130",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'131",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'132",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'133",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'134",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'135",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'136",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'137",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'138",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'139",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'140",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'141",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'142",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'143",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'144",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'145",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'146",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'147",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'148",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'149",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'150",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'151",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'152",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'153",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'154",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'155",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'156",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'157",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'158",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'159",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'160",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'161",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'162",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'163",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'164",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'165",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'166",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'167",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'168",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'169",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'170",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'171",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'172",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'173",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'174",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'175",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'176",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'177",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'178",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'179",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'180",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'181",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'182",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'183",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'184",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'185",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'186",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'187",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'188",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'189",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'190",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'191",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'192",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'193",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'194",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'195",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'196",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'197",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'198",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'199",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'200",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'201",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'202",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'203",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'204",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'205",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'206",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'207",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'208",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'209",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'210",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'211",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'212",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'213",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'214",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'215",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'216",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'217",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'218",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'219",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'220",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'221",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'222",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'223",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'224",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'225",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'226",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'227",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'228",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'229",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'230",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'231",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'232",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'233",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'234",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'235",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'236",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'237",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'238",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'239",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'240",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'241",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'242",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'243",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'244",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'245",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'246",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'247",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'248",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'249",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'250",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'251",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'252",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'253",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'254",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'255",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'256",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'257",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'258",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'259",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'260",
                            @"Stabilo Holiday Flipbook - 'Free Your True Colors'261",
                            
                            
                            ];
    
    NSMutableArray *images = [[NSMutableArray alloc] init];     //create an array and allocate space to store the image
    
    for (int i = 0; i < imageNames.count; i++) {
        [images addObject:[UIImage imageNamed:[imageNames objectAtIndex:i]]];
    }
    
    
    self.image.animationImages = images;            //Sets the images array to the animationImage
    self.image.animationDuration = 7;            // the image changed in 0.1second
    
    [self.view addSubview:self.image];
    [self.image startAnimating];
    
    
    
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

/*
#pragma mark - Navigation

// In a storyboard-based application, you will often want to do a little preparation before navigation
- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
    // Get the new view controller using [segue destinationViewController].
    // Pass the selected object to the new view controller.
}
*/

@end
